### ISSUE TITLE
[Bug]: Issue setting variables in .env when migrating from previous iteration of the stack

### ISSUE THREAD

**Issue by jlevydev** [Panfactum/stack#10]
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

When migrating from the non-flake version of the stack and attempting to set environment variables it seems as if there are conflicts from an unknown file. Potentially as a result of a previous devenv set up in the same file location
![Screenshot from 2024-03-10 16-05-02](https://github.com/Panfactum/stack/assets/105033689/2612ba73-e995-4c9a-99e3-0b105b209c2f)

### Version

main (development branch)

### What primary components of the stack are you seeing the problem on?

nix

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fullykubed** [comment]
This sounds like an issue potentially with migrating from non-flake to flake version of devenv. I don't see any documentation on their site around making this migration, but please ensure you have removed all local cache files before making this transition (`.devenv`, `.direnv`, etc.).

Can you share your `.envrc`, `flake.nix`, `flake.lock`, and `devenv.nix`?

**Comment by jlevydev** [comment]
I tried clearing my caches but to no avail. See the files attached (saved as txt files since Github couldn't attach them as is).

[devenv.nix.txt](https://github.com/Panfactum/stack/files/14552415/devenv.nix.txt)
[flake.lock.txt](https://github.com/Panfactum/stack/files/14552416/flake.lock.txt)
[flake.nix.txt](https://github.com/Panfactum/stack/files/14552417/flake.nix.txt)
[.envrc.txt](https://github.com/Panfactum/stack/files/14552419/default.envrc.txt)

Also, should `.direnv/` be added to the `.gitignore`. Wasn't covered in the local/repo set up docs but seems wise.

**Comment by fullykubed** [comment]
I have identified the issue.

Conflicting settings values in `nix` are merged based on the concept of priority. `mkDefault` assigns a low priority (1000). Trying to merge two values with the same priority will result in an error.

I had thought that `mkDefault` would be sufficient for setting variables in the panfactum devenv. However, according to [these docs](https://github.com/cachix/devenv/blob/be7e8358c1d871021e3d24acc67e2beb41830e10/docs/integrations/dotenv.md?plain=1#L2), the variables read in from the `.env` file are also assigned the `mkDefault` priority. This creates the conflict you have witnessed.

The fix is to change all of the panfactum default variables to an _even_ lower priority (1001). Should be a simple enough change that I can release tomorrow.

**Comment by fullykubed** [comment]
This should be resolved on the latest update.

**Comment by jlevydev** [comment]
I'm still seeing the issue. I cleared my cache and attempted a rebuild. I'm pinned to main, is there something else I'd have to do to consume the update?

**Comment by fullykubed** [comment]
You cannot be pinned to main, only a specific commit. Please update your flake.lock. See the versioning / upgrading docs for specific instructions and best practices.

**Comment by fullykubed** [comment]
I think [this](https://www.tweag.io/blog/2020-05-25-flakes/) provides a good summary of the functionality you are looking for if you just need a quick primer on flakes, inputs, pinning, and upgrades.

**Comment by jlevydev** [comment]
Yup, it was user error, I pulled in the latest changes and I'm all good!
